baseURL = "localhost:1313"
languageCode = "en-US"
title = "STEAMConf 2019"
license = "GNU General Public License v3.0"
tags = "educacion, steam, education, steam"
tagline = "STEAMConf, 5th. International Education Conference"
description = "STEAMConf wants to visualize the vital importance of implementing programs and resources, which help to minimize the digital divide, gender imbalances and promote equal opportunities."
DefaultContentLanguage = "ca"
copyright = "© STEAMConf 2019"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""


[Languages]

[Languages.en]
title = "STEAMConf"
weight = 1
name = "EN"
languageCode = "en-US"

[Languages.es]
title = "STEAMConf"
weight = 2
name = "ES"
languageCode = "es-ES"

[Languages.ca]
title = "STEAMConf"
weight = 3
name = "CA"
languageCode = "ca-CA"
